version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management    
    container_name: rabbitmq
  Send:
    image: sender
    build:
      context: ./Send
      dockerfile: Dockerfile
    depends_on:
        - rabbitmq
  Receiver:
    image: receiver
    build:
      context: ./Receive
      dockerfile: Dockerfile
    depends_on:
        - rabbitmq
